services:
  sql-server-db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1777:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_USER=SA
      - MSSQL_SA_PASSWORD=GeoP&t#2022
    restart: "always"
    